environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '11'

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  # Get the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  # Install dependencies
  - yarn install --ignore-engines

test_script:
  - yarn build
  - appveyor-retry call yarn test

build: off
